- name: "PLAY 1: This playbook configures loopback interfaces on sandbox-iosxe-recomm-1.cisco.com using a cli_config module and a jinja"
  hosts: routers            # THIS WILL REFER TO THE HOST/GROUP THAT THIS PLAY IS TARGETING
  connection: network_cli   # FOR NETWORK DEVICES THE CONNECTION WILL BE 'network_cli'
  tasks:                    # BELOW TASKS IS WHERE EACH TASK IS DEFINED
    - name: "TASK 1: set time for pre-check"
      set_fact:
        mydate: "{{lookup('pipe','date +%Y-%m-%d_%H:%M')}}"
        date: "{{lookup('pipe','date +%Y-%m-%d')}}"
        epoch: "{{lookup('pipe','date +%s')}}"
      tags: "date"
      run_once: true

    - name: "TASK 2: set fact for pre-change filename which uses date"
      set_fact:
        pre_file: "./outputs/{{ inventory_hostname }}/pre_change/{{ mydate }}_{{ inventory_hostname }}.txt"

    - name: "TASK 3: ensure directory for each device exists pre-change output"
      file:
        path: ./outputs/{{ inventory_hostname }}/pre_change/
        state: directory

    - name: "TASK 4: send pre-change show commands"
      cli_command:
        command: '{{ item }}'
      loop:
        - "show ip interface brief"
        - "show interfaces"
        - "show ip route"
      register: show_result

    - name: "TASK 5: send the output of pre-change commands to a nice template and print it to a file"
      copy:
        content: "{{ lookup( 'template', '../templates/pre-post-template.j2') }}"
        dest: "outputs/{{ inventory_hostname }}/pre_change/{{ mydate }}_{{ inventory_hostname }}.txt"
        mode: 0664

    - name: "TASK 6: Configure the loopback interfaces that are listed in the host_vars/ directory"
      cli_config:
        config: "{{ lookup('template', '../templates/interface-template.j2') }}"
      register: cli_result    # save the output to the 'cli_result'

    - name: "TASK 7: set time for post-change"
      set_fact:
        mydate: "{{lookup('pipe','date +%Y-%m-%d_%H:%M')}}"
        date: "{{lookup('pipe','date +%Y-%m-%d')}}"
        epoch: "{{lookup('pipe','date +%s')}}"
      tags: "date"
      run_once: true

    - name: "TASK 8: ensure post-change directory exists"
      file:
        path: ./outputs/{{ inventory_hostname }}/post_change/
        state: directory

    - name: "TASK 9: set fact for post-check filename which uses date"
      set_fact:
        post_file: "./outputs/{{ inventory_hostname }}/post_change/{{ mydate }}_{{ inventory_hostname }}.txt"

    - name: "TASK 10: send post-change show commands"
      cli_command:
        command: '{{ item }}'
      loop:
        - "show ip interface brief"
        - "show interfaces"
        - "show ip route"
      register: show_result

    - name: "TASK 11: send the output of post-change commands to a nice template and print it to a file"
      copy:
        content: "{{ lookup( 'template', '../templates/pre-post-template.j2') }}"
        dest: "outputs/{{ inventory_hostname }}/post_change/{{ mydate }}_{{ inventory_hostname }}.txt"
        mode: 0664

    - name: "TASK 12: get diff of pre change vs post change output"
      command: >
        diff {{ pre_file }} {{ post_file }}
      register: difference
      failed_when: difference.rc > 1
      changed_when: difference.rc == 1

    - name: "Task 13: ensure diff directory exists"
      file:
        path: ./outputs/{{ inventory_hostname }}/diff/
        state: directory    

    - name: "Task 14: put diffs between pre and post change, if they exist, in the diff file for that device name"
      when: "difference.stdout is defined"
      copy:
        content: "{{ difference.stdout }}"
        dest: "./outputs/{{ inventory_hostname }}/diff/diff_{{ mydate }}_{{ inventory_hostname }}.txt"